version: "3.3"
services:
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network
    environment:
      - MYSQL_DATABASE=demo1
      - MYSQL_ROOT_PASSWORD=password

  server:
    build: server
    restart: always
    ports:
      - target: 20001
        published: 20001
        protocol: udp
    networks:
      - backend-network
      
  webapp:
    build: webapp
    restart: always
    ports:
      - 5000:5000
      
volumes:
  db-data:
networks:
  backend-network:
